package eom.tri.weather.model

import com.fasterxml.jackson.annotation.JsonProperty
import org.springframework.data.annotation.Id

data class MidTemperatureForecast (
        @Id
        val id: Long? = null,
        val regId: String,
        val refDate: String,
        val taMin3: String,
        val taMin3Low: String,
        val taMin3High: String,
        val taMax3: String,
        val taMax3Low: String,
        val taMax3High: String,
        val taMin4: String,
        val taMin4Low: String,
        val taMin4High: String,
        val taMax4: String,
        val taMax4Low: String,
        val taMax4High: String,
        val taMin5: String,
        val taMin5Low: String,
        val taMin5High: String,
        val taMax5: String,
        val taMax5Low: String,
        val taMax5High: String,
        val taMin6: String,
        val taMin6Low: String,
        val taMin6High: String,
        val taMax6: String,
        val taMax6Low: String,
        val taMax6High: String,
        val taMin7: String,
        val taMin7Low: String,
        val taMin7High: String,
        val taMax7: String,
        val taMax7Low: String,
        val taMax7High: String,
        val taMin8: String,
        val taMin8Low: String,
        val taMin8High: String,
        val taMax8: String,
        val taMax8Low: String,
        val taMax8High: String,
        val taMin9: String,
        val taMin9Low: String,
        val taMin9High: String,
        val taMax9: String,
        val taMax9Low: String,
        val taMax9High: String,
        val taMin10: String,
        val taMin10Low: String,
        val taMin10High: String,
        val taMax10: String,
        val taMax10Low: String,
        val taMax10High: String
        )
