package eom.tri.weather.model

import com.fasterxml.jackson.annotation.JsonProperty
import org.springframework.data.annotation.Id

data class MidTemperatureForecast (
        @Id
        val id: Long? = null,
        val regId: String,
        val refDate: String,
        @field:JsonProperty("3일후_최저_예상기온") val taMin3: String,
        @field:JsonProperty("3일후_최저_예상기온_하한범위")val taMin3Low: String,
        @field:JsonProperty("3일후_최저_예상기온_상한범위") val taMin3High: String,
        @field:JsonProperty("3일후_최고_예상기온") val taMax3: String,
        @field:JsonProperty("3일후_최고_예상기온_하한범위") val taMax3Low: String,
        @field:JsonProperty("3일후_최고_예상기온_상한범위") val taMax3High: String,
        @field:JsonProperty("4일후_최저_예상기온") val taMin4: String,
        @field:JsonProperty("4일후_최저_예상기온_하한범위") val taMin4Low: String,
        @field:JsonProperty("4일후_최저_예상기온_상한범위") val taMin4High: String,
        @field:JsonProperty("4일후_최고_예상기온") val taMax4: String,
        @field:JsonProperty("4일후_최고_예상기온_하한범위") val taMax4Low: String,
        @field:JsonProperty("4일후_최고_예상기온_상한범위") val taMax4High: String,
        @field:JsonProperty("5일후_최저_예상기온") val taMin5: String,
        @field:JsonProperty("5일후_최저_예상기온_하한범위") val taMin5Low: String,
        @field:JsonProperty("5일후_최저_예상기온_상한범위") val taMin5High: String,
        @field:JsonProperty("5일후_최고_예상기온") val taMax5: String,
        @field:JsonProperty("5일후_최고_예상기온_하한범위") val taMax5Low: String,
        @field:JsonProperty("5일후_최고_예상기온_상한범위") val taMax5High: String,
        @field:JsonProperty("6일후_최저_예상기온") val taMin6: String,
        @field:JsonProperty("6일후_최저_예상기온_하한범위") val taMin6Low: String,
        @field:JsonProperty("6일후_최저_예상기온_상한범위") val taMin6High: String,
        @field:JsonProperty("6일후_최고_예상기온") val taMax6: String,
        @field:JsonProperty("6일후_최고_예상기온_하한범위") val taMax6Low: String,
        @field:JsonProperty("6일후_최고_예상기온_상한범위") val taMax6High: String,
        @field:JsonProperty("7일후_최저_예상기온") val taMin7: String,
        @field:JsonProperty("7일후_최저_예상기온_하한범위") val taMin7Low: String,
        @field:JsonProperty("7일후_최저_예상기온_상한범위") val taMin7High: String,
        @field:JsonProperty("7일후_최고_예상기온") val taMax7: String,
        @field:JsonProperty("7일후_최고_예상기온_하한범위") val taMax7Low: String,
        @field:JsonProperty("7일후_최고_예상기온_상한범위") val taMax7High: String,
        @field:JsonProperty("8일후_최저_예상기온") val taMin8: String,
        @field:JsonProperty("8일후_최저_예상기온_하한범위") val taMin8Low: String,
        @field:JsonProperty("8일후_최저_예상기온_상한범위") val taMin8High: String,
        @field:JsonProperty("8일후_최고_예상기온") val taMax8: String,
        @field:JsonProperty("8일후_최고_예상기온_하한범위") val taMax8Low: String,
        @field:JsonProperty("8일후_최고_예상기온_상한범위") val taMax8High: String,
        @field:JsonProperty("9일후_최저_예상기온") val taMin9: String,
        @field:JsonProperty("9일후_최저_예상기온_하한범위") val taMin9Low: String,
        @field:JsonProperty("9일후_최저_예상기온_상한범위") val taMin9High: String,
        @field:JsonProperty("9일후_최고_예상기온") val taMax9: String,
        @field:JsonProperty("9일후_최고_예상기온_하한범위") val taMax9Low: String,
        @field:JsonProperty("9일후_최고_예상기온_상한범위") val taMax9High: String,
        @field:JsonProperty("10일후_최저_예상기온") val taMin10: String,
        @field:JsonProperty("10일후_최저_예상기온_하한범위") val taMin10Low: String,
        @field:JsonProperty("10일후_최저_예상기온_상한범위") val taMin10High: String,
        @field:JsonProperty("10일후_최고_예상기온") val taMax10: String,
        @field:JsonProperty("10일후_최고_예상기온_하한범위") val taMax10Low: String,
        @field:JsonProperty("10일후_최고_예상기온_상한범위") val taMax10High: String
        )
