spring:
  r2dbc:
    url: r2dbc:mysql://mysql:3306/weather?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: stephano-tri
    pool:
      initial-size: 10
      max-size: 100
      validation-query: SELECT 1

logging:
  level:
    org.springframework.r2dbc.core: debug

gov:
  api:
    url: https://apis.data.go.kr/1360000
    key: your_own_key

