package eom.tri.weather.model.GovernmentAPI.typed

import com.fasterxml.jackson.annotation.JsonProperty

data class MidTermTmpForecast(
    @field:JsonProperty("regId") val regId: String,
    @field:JsonProperty("taMin3") val taMin3: String,
    @field:JsonProperty("taMin3Low") val taMin3Low: String,
    @field:JsonProperty("taMin3High") val taMin3High: String,
    @field:JsonProperty("taMax3") val taMax3: String,
    @field:JsonProperty("taMax3Low") val taMax3Low: String,
    @field:JsonProperty("taMax3High") val taMax3High: String,
    @field:JsonProperty("taMin4") val taMin4: String,
    @field:JsonProperty("taMin4Low") val taMin4Low: String,
    @field:JsonProperty("taMin4High") val taMin4High: String,
    @field:JsonProperty("taMax4") val taMax4: String,
    @field:JsonProperty("taMax4Low") val taMax4Low: String,
    @field:JsonProperty("taMax4High") val taMax4High: String,
    @field:JsonProperty("taMin5") val taMin5: String,
    @field:JsonProperty("taMin5Low") val taMin5Low: String,
    @field:JsonProperty("taMin5High") val taMin5High: String,
    @field:JsonProperty("taMax5") val taMax5: String,
    @field:JsonProperty("taMax5Low") val taMax5Low: String,
    @field:JsonProperty("taMax5High") val taMax5High: String,
    @field:JsonProperty("taMin6") val taMin6: String,
    @field:JsonProperty("taMin6Low") val taMin6Low: String,
    @field:JsonProperty("taMin6High") val taMin6High: String,
    @field:JsonProperty("taMax6") val taMax6: String,
    @field:JsonProperty("taMax6Low") val taMax6Low: String,
    @field:JsonProperty("taMax6High") val taMax6High: String,
    @field:JsonProperty("taMin7") val taMin7: String,
    @field:JsonProperty("taMin7Low") val taMin7Low: String,
    @field:JsonProperty("taMin7High") val taMin7High: String,
    @field:JsonProperty("taMax7") val taMax7: String,
    @field:JsonProperty("taMax7Low") val taMax7Low: String,
    @field:JsonProperty("taMax7High") val taMax7High: String,
    @field:JsonProperty("taMin8") val taMin8: String,
    @field:JsonProperty("taMin8Low") val taMin8Low: String,
    @field:JsonProperty("taMin8High") val taMin8High: String,
    @field:JsonProperty("taMax8") val taMax8: String,
    @field:JsonProperty("taMax8Low") val taMax8Low: String,
    @field:JsonProperty("taMax8High") val taMax8High: String,
    @field:JsonProperty("taMin9") val taMin9: String,
    @field:JsonProperty("taMin9Low") val taMin9Low: String,
    @field:JsonProperty("taMin9High") val taMin9High: String,
    @field:JsonProperty("taMax9") val taMax9: String,
    @field:JsonProperty("taMax9Low") val taMax9Low: String,
    @field:JsonProperty("taMax9High") val taMax9High: String,
    @field:JsonProperty("taMin10") val taMin10: String,
    @field:JsonProperty("taMin10Low") val taMin10Low: String,
    @field:JsonProperty("taMin10High") val taMin10High: String,
    @field:JsonProperty("taMax10") val taMax10: String,
    @field:JsonProperty("taMax10Low") val taMax10Low: String,
    @field:JsonProperty("taMax10High") val taMax10High: String,
)
