package eom.tri.weather.persistence

import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Table

@Table("mid_term_temp_forecast")
data class MidTermForecastTempEntity (
    @Id
    val id: Long? = null,
    val regId: String,
    val refDate: String,
    val taMin_3: String,
    val taMin_3Low: String,
    val taMin_3High: String,
    val taMax_3: String,
    val taMax_3Low: String,
    val taMax_3High: String,
    val taMin_4: String,
    val taMin_4Low: String,
    val taMin_4High: String,
    val taMax_4: String,
    val taMax_4Low: String,
    val taMax_4High: String,
    val taMin_5: String,
    val taMin_5Low: String,
    val taMin_5High: String,
    val taMax_5: String,
    val taMax_5Low: String,
    val taMax_5High: String,
    val taMin_6: String,
    val taMin_6Low: String,
    val taMin_6High: String,
    val taMax_6: String,
    val taMax_6Low: String,
    val taMax_6High: String,
    val taMin_7: String,
    val taMin_7Low: String,
    val taMin_7High: String,
    val taMax_7: String,
    val taMax_7Low: String,
    val taMax_7High: String,
    val taMin_8: String,
    val taMin_8Low: String,
    val taMin_8High: String,
    val taMax_8: String,
    val taMax_8Low: String,
    val taMax_8High: String,
    val taMin_9: String,
    val taMin_9Low: String,
    val taMin_9High: String,
    val taMax_9: String,
    val taMax_9Low: String,
    val taMax_9High: String,
    val taMin_10: String,
    val taMin_10Low: String,
    val taMin_10High: String,
    val taMax_10: String,
    val taMax_10Low: String,
    val taMax_10High: String
    )
